apiVersion: v1
kind: ConfigMap
metadata:
  name: memstore-config
  namespace: memstore
data:
  loglevel: debug
#  peers: memstore-0,memstore-1,memstore-2
  dns: memstore-internal.memstore.svc.cluster.local
  dns-interval: 5s
  statefulset: "true"
  ready: "false"
  config-port: "7999"
