apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memstore
  template:
    metadata:
      labels:
        app: memstore
    spec:
      containers:
      - name: memstore
        image: fortio/memstore:latest
